territorylist = ["BW","BS","CK","ER","EF","FL","MB","MD","RW","RS","WF","WW"]
rolelist = ['Bruiser', 'Dex', 'Group Healer', 'Zerg Healer', 'Support', 'Assassin']
weaponlist = ['Sword and Shield', 'Rapier', 'Hatchet', 'Spear', 'Greatsword', 'Great Axe', 'War Hammer', 'Blunderbuss', 'Musket', 'Bow', 'Fire Staff', 'Ice Gauntlet', 'Void Gauntlet', 'Life Staff']
abilitylist = ['Stoneform' ,'Detonate', 'Grasping Vines', 'Cannon Blast', 'Bile Bomb', 'Dark Ascent']
weightlist = ['Light', 'Medium', 'Heavy']